### ISSUE TITLE
CPANEL - INFO - Release 27-02-2017

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/legacy#207]
Hello Team,

Finally we have the januari update ready. We have been struggling a bit with the server, @DWetherilt  has been very busy lately, so we now decided to merge to another dev server (the STONISH server from Bruno). This way, we lift the burden of @DWetherilt's shoulders in these busy times. Thanks a lot for all the help with this hosting Darren! 
We did have some trouble on the new server. Seems the server had more severe PHP checks, so we had to rewrite some code (warnings and info messages were triggered, blocking certain parts of the site). Extra effort, but ofcourse, better written php code is a plus ;-)

This is the link to the new test website : dev.stonish.net

We started again from a clean DB, so this means I need to reset your pwd's again perhaps. If you are unable to log on, please sent me a pm on Facebook and I will reset your pwd. Also there is no IP security at this server, so please, do not share this link with anyone. Even though the current layout will be overhauled, we still want to keep it as much of a surprice as possible.

The biggest change in this update, is the 'completion' of the menu section. You can now add authors on every single title you add to a menu disk. We've also done a complete analysis for a new 
download section (I will start working on this in the next update), you can read this here : #186

Anyway, this is the complete list of this update :

**Main CPANEL**
- [x] A GO LIVE script is added
- [x] Removed some database update script problems. Fix #201 
- [x] Added better MYSQL error handling. #204  
- [x] Dir structure rearangement. #203  
- [x] Individual table structure changed and cpanel sections re-written. #198 
- [x] Technical doc section updated

**Menu Section**
- [x] Delete button placement. Fixes #192
- [x] "Legend" alignment fix. Fixes #190
- [x] Release year unclear fix. Fixes #191
- [x] intro credits inline. Fixes #196 
- [x] Select width fix #195 
- [x] open space problem/menu disk styling #189
- [x] We are now able to add authors to each title on a menu disk. #198 

**Game Section**
- [x] Falcon VGA and RGB Fixes #185 
- [x] Delete button placement. Fixes #194 
- [x] Added indexes all over the game section, dramatically lowering loading times when searching for games.

So what is planned next?

- New complete download section so the scene archivists in here can really do some serious work ;-)
- An automatic kind of interface to STONISH to fill up the menu section of the DB
- @Brume-AL & @Marcer75 also came up with some new ideas - more on that later
- Start working on the actual AL website for a first 'fase 1' release in the summer of 2017?? Let's hope! 
- And of course testing testing testing and bugfixing :-)

Here are the links to the previous updates :

This is the introduction post : #164
The first update was done on 06-08-2016 : #154
The second on 23-08-2016 : #158
The third on 03-01-2017 : #184 

I would like to end with the usual reminders :

Please remember : The new Atarilegend will be compatible for al mediums, meaning smartphones, tablets, laptops, PC's and even HD TV's. This means that it would be nice if it is tested in different resolutions (or just make the browser window less wide) and on different media. If you find something fishy, please let us know.

Please remember : The new Atarilegend uses multiple skins. Each skin has got its own CSS file. This means that each skin can have its own bugs. While testing, make sure to switch skins now and then. If you find a bug, let us know. Thanks.

If you have questions, remarks, suggestions, complaints ... let us know, post a thread in here. All help is welcome.

Cheers,
Maarten
