### ISSUE TITLE
CPANEL - INFO - Release 13-05-2017

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/legacy#215]
Hello all,

A little later but the April release is finally here. Lots of stuff this time : 

**CPANEL general**
- [x] created a custom upload button (input type=file) to fix responsivness in phone view on several places in the cpanel (eg. user detail page)
- [x] custom checkboxes created for the cpanel in all 3 skins
- [x] replaced all the tile php code to a common dir for usage in cpanel and main site
- [x] installed font awesome for SVT icons used in tiles and lists
- [x] started creating 'fun' tiles for the cpanel
        - Statistic tile : some random stats from the db
        - # of changes per month tile
        - Screenstar tile : completely new version with hoover css function - eg. cpanel game section --> removed this from the cpanel but will be used on the actual site
- [x] Every search field is now able to accept special chars eg. "Warlock's Quest".
- [x] added a "who's online" box on every page

**Main/stats page**
- [x] I have completely re-written this useless page by adding charts. This gives a nice overview of certain aspects of the database (more can be added) and it looks pretty neat - #214 

**User section**
- [x] Bug when making user inactive in user section on STONISH server
- [x] User statistics did not work since the game_download_info table was removed
- [x] Removed the pop up AGAIN from the user admin section as it was just not working correctly. I couldn't get the redirecting after a db modify right and in the end got seriously fed up. The fancy pop has it limitations and gave me too much headaches.
- [x] Removed all the unstable sh*t ajax from the quick_search_user left section. This thing was crashing all the time, the extra functions (like 'sent email' and 'deactivation of user') did not work anymore in it. And most of all, by using the ajax it was almost impossible for me to use this left section in any other pages (as the ajax code requires a 'hotspot' in the html file). So much headaches and all of this just to NOT PRESS a submit button. Don't worry, all original files are in tact (renamed them with the addition 'NOT USED', so if you feel like it one day, re-implement it all, just make it work  ;-) )
- [x] Did a complete replacement of the files in our dir structure. Everything USER related is now in the USER folder
- [x] Removed the old USER section as it was just not usefull anymore - Files contain the 'NOT USED' addition
- [x] added a column in the search results for phone landscape view (600px wide)
- [x] added real escape string when updating the username
- [x] greatly improved responsiveness of user_detail page by adding custom fileselector
- [x] added a check on extension when uploading an avatar
- [x] Updated the user_details. The SHA512 and SALT fields are now filled for pwd security. - see #85 - @stsilversurfer This is one that needs to be checked by you 
- [x] Karma resync is working again
- [x] Font awesome used in the list view - #118 
- [x] added option to mass activate users (instead of only deactivate)
- [x] added last visit and join date to user detail page

**Database update section**
- [x] Changed script nr 92 to 'change game_download_info' table. This table is needed in the project as it contains info on who downloaded what. I have added the game_download_id field to it

**Change log section**
- [x] removed bug - previous link did not work when changing search date

**Technical doc section**
- [x] Update of the download structure + info regarding new game_download_info table
- [x] Technical doc section added to top menu
- [x] Alignment issue of CONTENTS box in TOS skin

**Links section**
- [x] fixed responsiveness of 'add links' page for TOS and Picasso skin in phone view
- [x] Link mod list : Changed the layout a bit and added a correction for Chrome + added icons
- [x] Link modify detail : removed a bug when deleting link, made some changes for responsiveness, add the custom file selector
- [x] inactive field added to the link detail page - #115 
- [x] script created to add the inactive field to table WEBSITE

**Game section**
- [x] games list in Picasso - font size issue
- [x] games detail page - wrong link to download page in phone view only + layout fixes
- [x] Font awesome used in the list view - #118 
- [x] searching for games with special chars is now possible - #212 
- [x] new style checkboxes added on main game page
- [x] fixed size of category field in phone view - game detail page
- [x] custom upload button added for responsiveness in the game screenshot section
- [x] custom upload button added for responsiveness in the game boxscan section
- [x] review text field width fix in picasso and TOS skin for phoneview
- [x] add review - removed escape sting bug and added a fix on review score input
- [x] games music detail - added custom checkbox and upload field - fully responsive now
- [x] game comments page - layout changed, added icons, removed bugs (slashes)
- [x] game submissions page - layout is now the same as game comments page
- [x] game series - added new checkbox, removed delete bug
- [x] games detail page - all new checkbox + removal of 'wanted' bug

**Download section**
 - [x] custom upload button added for responsiveness 
 - [x] fixed responsiveness for complete section
 - [x] added icons in download detail page

**Article section**
 - [x] removed some bugs in article edit page
 - [x] removed screenshot bug from preview page
 - [x] Article screenshot page responsive and custom file selector added

**Company section**
 - [x] added real_excape when updating/inserting company - removed bug
 - [x] custom file selector added in Company edit screen

**Individuals section**
 - [x] custom file selector added in idividual edit screen
 - [x] added a lot more checks when deleting + removed deletion bug
 - [x] real_escape/special char bug removed

**Interview section**
 - [x] removed some bugs in interview edit page
 - [x] removed screenshot bug from preview page
 - [x] interview screenshot page responsive and custom file selector added
 - [x] the interviews help section is removed and replaced by the '?' help in each section

**Crew section**
 - [x] custom file selector added in crew edit screen - logo upload
 - [x] adding crews with special signs is now possible - eg, the warlock's 

**Menu section**
- [x] removed bug when searching for title using the input field and there are no results - menu detail page
- [x] Changed the order of the menu titles by title id - #213 
- [x] Searching for titles with special chars is now possible when adding a title to a menu
- [x] The searching for titles suffered from the log out ajax bug - #187 - This is now solved by adding a search button 
- [x] added custom checkbox and file selector
- [x] removed doc type bug
- [x] Stonish integration page removed for now
- [x] Section better responsive

**News section**
- [x] approve news - bug removed and search function added
- [x] custom file selector and checkboxes added

Here are the links to the previous updates :

Intro : #164
1 : #154
2 : #158
3 : #184 
4 : #207 
5 : #209

Cheers,
Maarten
