### ISSUE TITLE
MAIN SITE/CPANEL - INFO - Release 06-01-2018

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/legacy#402]
Hello team,

The December release got a little bit delayed, but we are now finally sharing the DB and the screenshots. Let's hope it gets spread in a good way! 

This is a summary of the updates : 

Changes:

**Development tooling**

- [x] Configure ESLint to check for Javascript issues #365 
- [x] Downgrade Docker PHP version to 5.6, same as dev & prod environment #364 
- [x] Cleanup tabs and newlines on template files #373
- [x] Refactor main scripts in a single file #377
- [x] New css classes for the html select tag #382
- [x] Use stricter MySQL modes with Docker #384
- [x] Added CSSComb to grunt #386 
- [x] Create folders to hold the DB backups and public dumps #389
- [x] Added script to purge old DB dumps #391
- [x] Publicize DB dumps on the "Open Database" tile #392
- [x] Introduce css class .standard_input #388
- [x] Introduce standard css classes for tables #397
- [x] Add grunt tasks for the php files, lint/fix #395

**Bugs**

- [x]  Insert game fact broken. Fixes #367: Fix insertion of game fact #368 
- [x]  Fixes #358: Fix inserting of individual AKA with apostrophe #374 
- [x]  Fix path to jQuery UI images #380 
- [x]  Fixed the website validation system that didn't work because of a wrong user_id column name. #387

**Links section**
- [x]  Remove the unused parent_category column (we do not support a tree
structure for categories anymore) #387
- [x]  Simplification of db schema and code by moving website description inside a description column #387 

**Features**
 - [x] Added opendb feature, anyone can download the database. #396
 - [x] Added some new graphics in the frontpage slider.

Here are the links to the previous updates :

Intro : #164
1 : #154
2 : #158
3 : #184 
4 : #207 
5 : #209
6 : #215
7 : #245
8 : #331
9 : #362 

Cheers,
Maarten
